apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grebride-prod

bases:
  - ../../../base/grebride-payment

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-payment
- path: service.yaml
  target:
    kind: Service
    labelSelector: app=grebride-payment
