apiVersion: v1
kind: Service
metadata:
  labels:
    app: grebride-booking
  name: grebride-booking-svc
  namespace: grebride
spec:
  ports:
  - name: goatport
    protocol: TCP
    targetPort: 8080
    port: 80
  selector:
    app: grebride-booking
  type: NodePort
