apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grebride-largeapp

bases:
  - ../../../base/large-app-25

patches:
- path: deployment1.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-1
- path: deployment2.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-2
- path: deployment3.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-3
- path: deployment4.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-4
- path: deployment5.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-5
- path: deployment6.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-6
- path: deployment7.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-7
- path: deployment8.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-8
- path: deployment9.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-9
- path: deployment10.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-10
- path: deployment11.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-11
- path: deployment12.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-12
- path: deployment13.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-13
- path: deployment14.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-14
- path: deployment15.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-15
- path: deployment16.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-16
- path: deployment17.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-17
- path: deployment18.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-18
- path: deployment19.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-19
- path: deployment20.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-20
- path: deployment21.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-21
- path: deployment22.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-22
- path: deployment23.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-23
- path: deployment24.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-24
- path: deployment25.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-25
#- path: service.yaml
#  target:
#    kind: Service
#    labelSelector: app=grebride-largeapp-1
