apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grebride-largeapp

bases:
  - ../../../base/large-app-5

patches:
- path: deployment1.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-1
- path: deployment2.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-2
- path: deployment3.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-3
- path: deployment4.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-4
- path: deployment5.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-largeapp-5
