apiVersion: v1
kind: Service
metadata:
  labels:
    app: grebride-largeapp-1
  name: grebride-largeapp-1-svc
  namespace: grebride-largeapp
spec:
  ports:
  - name: goatport
    protocol: TCP
    targetPort: 8080
    port: 80
  selector:
    app: grebride-largeapp-1
  type: NodePort
