apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grebride-largeapp-24
  name: grebride-largeapp-24
  namespace: grebride-largeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grebride-largeapp-24
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grebride-largeapp-24
    spec:
      containers:
      - image: eurogig/kustomizegoat:0.1
        name: grebride-largeapp-24

