apiVersion: apps/v1
kind: Deployment
metadata:
  name: grebride-payment
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - grebride-payment
            topologyKey: "kubernetes.io/hostname"
