apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment1.yaml
#  - service1.yaml
  - deployment2.yaml
#  - service2.yaml
  - deployment3.yaml
#  - service3.yaml
  - deployment4.yaml
#  - service4.yaml
  - deployment5.yaml
#  - service5.yaml
