apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grebride-stg

bases:
  - ../../../base/grebride-rating

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    labelSelector: app=grebride-rating
